import streamlit as st

from components.heatmap_viewer import render_heatmap_viewer
from components.history_table import render_history_table
from components.result_card import render_result_card
from components.upload import render_upload_section

st.set_page_config(
    page_title="Kidney Tumor ID System",
    page_icon="🫘",
    layout="wide",
    initial_sidebar_state="expanded",
)


def main():
    # Sidebar
    with st.sidebar:
        st.title("🫘 Kidney AI")
        st.markdown("---")

        # Navigation
        nav_selection = st.radio("Navigation", ["New Prediction", "Case History"])

        st.markdown("---")

        # Disclaimer
        st.warning(
            """
        **DISCLAIMER**

        This tool is generated by an AI decision-support system
        for **research purposes only**.
        It is NOT a clinical diagnosis.
        Always consult a qualified radiologist or
        physician for medical decisions.
        """
        )

        st.markdown("---")
        st.markdown("v0.1.0 | Fast & Accurate")

    # Main content
    if nav_selection == "New Prediction":
        st.title("Kidney Tumor Identification System")
        st.markdown(
            "Upload a CT scan to detect the presence of Cysts, Stones, Tumors, or Normal tissue."
        )

        render_upload_section()

        st.markdown("---")

        if "prediction_result" in st.session_state:
            render_heatmap_viewer()
            render_result_card()

    elif nav_selection == "Case History":
        render_history_table()


if __name__ == "__main__":
    main()
